---
functional:
  - Сайт должен отображать товары с названием, рейтингом, ценой со скидкой и без
  - Сайт должен иметь 2 вида users - админ, пользователь
  - Сайт должен обеспечивать возможность пользователям выбирать и оплачивать заказы
  - На сайте должен быть фильтр по товарам с пограничным выводом по названию/, рейтингу, цене, со скидкой или без, цвету, размеру и т.д.
  - На сайте должна быть корзина для добавления товаров с последующей оплатой или удалением из корзины товаров
  - На сайте должен быть поиск по ключевому слову
non-functional:
  - Сайт должен быть производительным по скорости работы и объема входящего трафика
  - Сайт должен быть безопасным (защита данных пользователей и администраторов)
  - Сайт должен быть адаптивным (браузеры с последними версиями и на различных мобильных устройствах устройствах)
  - Сайт должен быть SPA-приложением (не перезагружается страница)
  - На сайте пользователь должен иметь возможность просматривать содержимое своей корзины
  - Корзина пользователя должна хранится в сессии браузера
  - У заказчика должен быть доступ к администрированию интернет магазина (создание, редактирование, удаление товаров)
implicit:
  - На сайте должна быть форма регистрации пользователя (чтение товаров, оформление заказа, редактирование заказа, оплата заказа)
  - Обязательные требования при регистрации пользователя (Фамилия, Имя, Логин, Пароль, Подтверждение пароля, Номер телефона, Город, Адрес проживания)
  - На сайте должна быть форма входа в личный кабинет интернет-магазина пользователя
  - Корзина пользователя должна сохранятся на сайте в его личном кабинете, чтобы была возможность оплатить или отредактировать заказ в следующих сессиях
  - Личный кабинет пользователя должен синхронизироваться на всех устройствах и всех браузерах
  - В личном кабинете пользователя должен быть доступ к отслеживанию статусов заказа (Ожидает оплату, Оплачен, Получен)
  - В личном кабинете пользователя должна храниться история предыдущих заказов со всеми статусами и возможностями посмотреть прошлые заказы 
